import logging
from flask import current_app
from flask_mail import Message
from . import mail

logger = logging.getLogger(__name__)

def send_faculty_alert(student_data, risk_level, predicted_grade):
    """
    Sends an immediate email alert to faculty when a student is flagged as High Risk.
    This is the 'Physical Intervention' part of the Action Router.
    """
    # Double-check risk level to avoid spam
    if risk_level.lower() != 'high':
        return

    try:
        # Get the faculty email from config (or default to the sender)
        faculty_email = current_app.config.get('MAIL_USERNAME')
        
        if not faculty_email:
            logger.warning("Faculty email not configured. Skipping alert.")
            return

        subject = f"🚩 URGENT INTERVENTION: High Risk Student Detected"
        
        body = f"""
        ACADEMIC RISK INTERVENTION SYSTEM
        =================================
        
        A student has been flagged for immediate intervention.
        
        --- RISK ASSESSMENT ---
        Risk Category: {risk_level.upper()}
        Predicted Final Grade: {predicted_grade}/20
        
        --- STUDENT METRICS ---
        Age: {student_data.get('age', 'N/A')}
        Previous Failures: {student_data.get('failures', 0)}
        Absences: {student_data.get('absences', 0)}
        Study Time: {student_data.get('studytime', 0)} (Scale 1-4)
        
        --- ACTION REQUIRED ---
        1. Schedule a one-on-one counseling session within 24 hours.
        2. Review the 'Academic Crisis' recovery plan with the student.
        
        [Generated by AI Student Mentor Device]
        """
        
        msg = Message(
            subject=subject,
            recipients=[faculty_email], # In a real app, this would be a specific counselor's email
            body=body
        )
        
        mail.send(msg)
        logger.info("High Risk Alert sent to faculty successfully.")

    except Exception as e:
        # We log the error but do NOT crash the app, so the student still gets their result
        logger.error(f"Failed to send faculty alert: {e}")